#
name: docker build / push / deploy
on:
  push:
  #   branches:
  #     - main
  #   tags:
  #     - v*
  # pull_request:

env:
  PROJECT_ID: quelpoke
  IMAGE_NAME: quelpoke
  REGION: europe-west9
  REGISTRY: student-yann

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: set short sha env
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: set registry domain
        run: echo "REGISTRY_DOMAIN=${REGION}-docker.pkg.dev" >> $GITHUB_ENV

      - name: set image name env
        run: echo "IMAGE_NAME=${REGISTRY_DOMAIN}/${PROJECT_ID}/${REGISTRY}:${GITHUB_SHA_SHORT}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${PROJECT_ID}
          credentials_json: ${ secrets.SERVICE_ACCOUNT_KEY }

      - name: gcloud configure docker 
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: docker build 
        run: docker build --tag=${IMAGE_NAME} .
      
      - name: docker push 
        run: docker push ${IMAGE_NAME}