name: deploy production
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        default: prod
      version:
        description: 'Quelpoke version'
        default: '2.5.3'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "${{ github.event.inputs.version }}"
